version: '3'

# docker rm $(docker ps -a -q) && docker volume prune -f

services:
#  mysql:
#    image: mysql:8
#    command: --mysql-native-password=ON
#    environment:
#      MYSQL_ROOT_PASSWORD: "love"
#      MYSQL_DATABASE: golang
#    ports:
#      - '3306:3306'
#    volumes:
#      - './init/db_tables/:/docker-entrypoint-initdb.d/'

  mongodb:
    image: 'mongo:5'
    environment:
      - MONGO_INITDB_DATABASE=ternura
    ports:
      - '27017-27019:27017-27019'

#  redis:
#    image: 'redis'
#    ports:
#      - '6379:6379'